kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir
  namespace: kafka-cluster
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
